### ISSUE TITLE
코드 수정 요청 사항

### ISSUE THREAD

**Issue by snoopspy** [qoqokim/pcap-test#1]
https://github.com/qoqokim/pcap-test/commit/072193d1e7fbc9016520bc9aacc4ef81ce2a71ce#r38443938

https://github.com/qoqokim/pcap-test/commit/072193d1e7fbc9016520bc9aacc4ef81ce2a71ce#r38443948

**Comment by qoqokim** [comment]
done in

55d334e85b19d9a4fd8bb9ca9a1c941a3d956815
364601adf757c386782516563ddcf37bbfee4c99

**Comment by snoopspy** [comment]
수고하셨습니다.
